
CREATE TABLE IF NOT EXISTS USUARIOS 
(
	IDCLIENTE INT(11) PRIMARY KEY AUTO_INCREMENT ,
    USU_NOMBRES varchar(60) NOT NULL,
    USU_DNI char(8) NOT NULL, 
    USU_APELLIDOS varchar(60) NOT NULL,
    USU_EMAIL varchar(120) NOT NULL,
    USU_ALIAS varchar(60) NOT NULL,
    USU_DIRECCION varchar(100) NOT NULL,
    USU_SEXO char(1) NOT NULL,
    USU_FECH_NAC datetime NOT NULL,
    USU_CONTRASENIA varchar(30) NOT NULL,
    USU_FEC_REG datetime 
);



CREATE TABLE IF NOT EXISTS CATEGORIA 
(
	IDCATEGORIA INT(11) PRIMARY KEY AUTO_INCREMENT ,
    CAT_NOMBRE varchar(60) NOT NULL,
    CAT_DESCRIPCION varchar(80) NOT NULL, 
    CAT_ESTADO tinyint(4) NOT NULL
);



CREATE TABLE IF NOT EXISTS PRODUCTO 
(
	IDPRODUCTO INT(11) PRIMARY KEY AUTO_INCREMENT ,
    PRO_NOMBRE varchar(60) NOT NULL,
    PRO_DESCRIPCION varchar(100) NOT NULL,
    PRO_PRECIO decimal(10,2) NOT NULL,
    PRO_STOCK int NOT NULL,
    IDCATEGORIA INT(11),
    CONSTRAINT FK_IDCATEGORIA
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);

ALTER TABLE PRODUCTO ADD PROD_IMG  varchar(180) NOT NULL;

CREATE TABLE IF NOT EXISTS PRODUCTO_CATEGORIA
(
	ID_PRO_CAT INT(11) PRIMARY KEY AUTO_INCREMENT ,
    IDPRODUCTO INT(11) NOT NULL,
    IDCATEGORIA INT(11) NOT NULL,
    CONSTRAINT FK_IDCATEGORIAS FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
    CONSTRAINT FK_IDPRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);


CREATE TABLE IF NOT EXISTS ORDERS
(
	IDORDERS INT(11) PRIMARY KEY AUTO_INCREMENT ,
    IDCLIENTE INT(11) NOT NULL,
    ORD_MONTO_PAGADO decimal(10,4) NOT NULL,
    ORD_FECH_REG datetime NOT NULL,
    ORD_EMAIL varchar(120) NOT NULL,
    ORD_DIRECCION  varchar(120) NOT NULL,
    CONSTRAINT FK_IDCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES USUARIOS(IDCLIENTE)
);


CREATE TABLE IF NOT EXISTS ORDERS_DETAILS
(
	ID_ORDERS_DETAILS INT(11) PRIMARY KEY AUTO_INCREMENT ,
    IDORDERS INT(11) NOT NULL,
    IDPRODUCTO INT(11) NOT NULL,
    ORD_DET_PRECIO  decimal(10,4) NOT NULL,
    ORD_DET_CANTIDAD   INT(11) NOT NULL,
    CONSTRAINT FK_IDORDERS FOREIGN KEY (IDORDERS) REFERENCES ORDERS(IDORDERS),
    CONSTRAINT FK_IDPRODUCTOS FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);


/** USAR LO SIGUIENTE EN CASO DE NO CONECTARSE A LA BASE DE DATOS */
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
flush privileges;


ALTER TABLE usuarios MODIFY USU_CONTRASENIA varchar(120);
ALTER TABLE orders MODIFY ORD_MONTO_PAGADO decimal(10,2);
ALTER TABLE orders_details MODIFY ORD_DET_PRECIO decimal(10,2);
ALTER TABLE usuarios MODIFY USU_FECH_NAC date;

ALTER TABLE producto DROP COLUMN PROD_IMG;

CREATE TABLE IF NOT EXISTS PRODUCTO_IMG
(
	ID_PRO_IMG INT(11) PRIMARY KEY AUTO_INCREMENT ,
    IDPRODUCTO INT(11) NOT NULL,
    PRO_IMG VARCHAR(120) NOT NULL,
    CONSTRAINT FK_IDPRODUCT FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);


CREATE TABLE IF NOT EXISTS CALIFICACIONES
(
	IDCALIFICACION INT(11) PRIMARY KEY AUTO_INCREMENT ,
    IDPRODUCTO INT(11) NOT NULL,
    CA_CALIFICACION decimal(10,2) NOT NULL,
    CA_COMENTARIO VARCHAR(120) NOT NULL,
    CONSTRAINT FK_IDPRODUCTS FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);


CREATE TABLE PROMOCIONES(
	IDPROMOCION INT PRIMARY KEY NOT NULL,
    PROM_NOMRE VARCHAR(50) NOT NULL,
    PROM_DESCUENTO FLOAT NOT NULL,
    PROM_FECHA_INICIO DATE NOT NULL,
    PROM_FECHA_FIN DATE NOT NULL,
    IDPRODUCTO INT (11),
    CONSTRAINT FK_IDPRODUCTO
    FOREIGN KEY (IDPRODUCTO) REFERENCES producto(IDPRODUCTO)
);

ALTER TABLE usuarios ADD USU_CALIFICACION decimal(10,2);
ALTER TABLE usuarios ADD USU_TYPE TINYINT not null;
ALTER TABLE producto DROP COLUMN IDCATEGORIA;
ALTER TABLE producto MODIFY PRO_DESCRIPCION varchar(200);
ALTER TABLE usuarios DROP COLUMN USU_CALIFICACION;
ALTER TABLE orders DROP COLUMN ORD_EMAIL;
ALTER TABLE categoria DROP COLUMN CAT_ESTADO;   
ALTER TABLE calificaciones ADD CA_FECHA date not null;
ALTER TABLE calificaciones ADD IDCLIENTE int not null;
SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE calificaciones ADD CONSTRAINT fk_IDCLIENT FOREIGN KEY (IDCLIENTE) REFERENCES USUARIOS(IDCLIENTE);